# GET http://localhost:5500

POST http://localhost:5500 HTTP/1.1

#   content-type:application/json

#   {
#     "id":2,
#     "designation": "test Prestataire",
#     "telephone": "test 243827485588",
#     "email": "test email@email.com",
#     "adresse": "test Kinshasa-Gombe",
#     "gerant": "test Gerant A",
#     "annee_experience": 2,
#   }
{
  "id": 2,
  "designation": "Prestataire 2",
  "telephone": "243827485588",
  "email": "email@email.com",
  "adresse": "Kinshasa-Gombe",
  "gerant": "Gerant A",
  "forme_juridique": {
    "id": 1,
    "libelle": "SARL"
  },
  "secteur_intervention": {
    "id": 1,
    "libelle": "Secteur A"
  },
  "annee_experience": 2
}

